CREATE TABLE networks (
    id SERIAL PRIMARY KEY,
    code VARCHAR(36) NOT NULL,
    name VARCHAR(36) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_networks_id" ON markets ("id");