CREATE TABLE coins (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(36) NOT NULL,
    name VARCHAR(36) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_coins_id" ON coins ("id");