// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Assignment struct {
	ID        int32            `json:"id"`
	MarketID  int32            `json:"marketId"`
	CoinID    int32            `json:"coinId"`
	NetworkID int32            `json:"networkId"`
	Active    pgtype.Bool      `json:"active"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
}

type Coin struct {
	ID        int32            `json:"id"`
	Symbol    string           `json:"symbol"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
}

type Market struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Description string           `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	UpdatedAt   pgtype.Timestamp `json:"updatedAt"`
}

type Network struct {
	ID        int32            `json:"id"`
	Code      string           `json:"code"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
}
